services:
  # Web Service
  - type: web
    name: jnd-shortlinks
    runtime: docker
    plan: free
    envVars:
      - key: APP_KEY
        value: base64:yMqKzVdktPIKFJmVjKIDpYGMQzFOPKyG6V+9WBis4AU=
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "true"
      - key: APP_URL
        value: https://jnd-shortlinks.onrender.com
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: debug
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_DRIVER
        value: file
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: jnd-shortlinks-db
          property: connectionString

# PostgreSQL Database
databases:
  - name: jnd-shortlinks-db
    plan: free
    databaseName: jnd_shortlinks
